### ISSUE TITLE
'Confirm' does not show the Pass/Fail for the Normality, QQ location or QQ scale

### ISSUE THREAD

**Issue by markdouglasphd** [ITISFoundation/publication-IEC62209#20]
Please add 'Pass' or 'Fail' in the same text color as the pass/fail of 'Acceptance Criteria'

![2023-05-01 01_00_34-oSPARC - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/131360748/235430767-a3b3eacf-09b0-42dd-8708-ef92b0d25510.png)

**Comment by SCA-ZMT** [comment]
@odeimaiz I added the pass/fail strings here: https://github.com/ITISFoundation/IEC62209-service/pull/79
