### ISSUE TITLE
'Acceptance Criteria' says 'Pass' when it should say 'Fail'

### ISSUE THREAD

**Issue by markdouglasphd** [ITISFoundation/publication-IEC62209#24]
v.1.0.12

In the 'Confirm' window for the example below, I loaded data that fails (there is one red dot that is outside the mpe).
But the 'Acceptance Criteria' shows 'Pass'. It should say 'Fail'

![2023-05-01 11_05_51-](https://user-images.githubusercontent.com/131360748/235433542-fdb3cb89-7afc-4a0e-b5d7-9b3634c48f32.png)

**Comment by SCA-ZMT** [comment]
will be fixed here: https://github.com/ITISFoundation/IEC62209-service/pull/79
