### ISSUE TITLE
report should not say 'successfully completed' if the data fails

### ISSUE THREAD

**Issue by markdouglasphd** [ITISFoundation/publication-IEC62209#28]
v1.0.12

if either of the two pass/fail criteria (acceptance criteria, or nrmse) fails, the text in the report should be changed.
Change "successfully completed" to "failed to complete"

![2023-05-01 11_34_18-ModelCreationReport (8) pdf - Adobe Acrobat Pro (64-bit)](https://user-images.githubusercontent.com/131360748/235435831-b4859827-220b-48b7-8bd2-b9ce6310fa8d.png)

**Comment by SCA-ZMT** [comment]
will be fixed by https://github.com/ITISFoundation/IEC62209-service/pull/79
