### ISSUE TITLE
add sentence to figure of acceptance data in report

### ISSUE THREAD

**Issue by markdouglasphd** [ITISFoundation/publication-IEC62209#29]
Please add a sentence to the end of the figure caption and make a change to the 2nd sentence:
"Deviations in SAR10g compared to the target values for the test configurations. The deviations are compared to the maximum permissible errors (mpe; dashed lines). Blue dots are inside the mpe. Any red dots are outside the mpe."

![2023-05-01 11_41_21-ModelCreationReport (8) pdf - Adobe Acrobat Pro (64-bit)](https://user-images.githubusercontent.com/131360748/235436424-246d125e-4947-4ea7-980f-7ee1ce9f035d.png)

**Comment by markdouglasphd** [comment]
This should apply to all three reports.

**Comment by SCA-ZMT** [comment]
will be fixed in https://github.com/ITISFoundation/IEC62209-service/pull/79
