### ISSUE TITLE
change 'passes' to either 'successfully completed' or 'failed to complete' in the model confirmation report

### ISSUE THREAD

**Issue by markdouglasphd** [ITISFoundation/publication-IEC62209#30]
v1.0.12
In the model confirmation report:

For consistency with the model creation report, change 'pass' to 'successfully completed' if all criteria pass.
And change 'successfully completed' to 'failed to complete' if any criteria fails.

![2023-05-01 11_55_15-ModelConfirmationReport (2) pdf and 1 more page - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/131360748/235438137-10fc2175-7535-46e7-95b6-ca87a3ecd16b.png)

**Comment by SCA-ZMT** [comment]
@markdouglasphd Should I simply remove the sentence `In combination with the model confirmation step, the system can therefore be considered successfully validated.` if the system fails, or would you add a different sentence instead?

**Comment by markdouglasphd** [comment]
Hi @SCA-ZMT. Let's remove that sentence. Thanks for noticing.
