### ISSUE TITLE
the generated report in 'Verify' does not open

### ISSUE THREAD

**Issue by markdouglasphd** [ITISFoundation/publication-IEC62209#33]
v1.0.12

The file that is created by 'Generate Report' in the 'Verify' window is corrupted or something. I can't open it.

![2023-05-01 14_30_05-Adobe Acrobat](https://user-images.githubusercontent.com/131360748/235451953-f11210bc-af3a-4377-833b-bdb80142a8cf.png)

**Comment by SCA-ZMT** [comment]
hi @markdouglasphd I cannot reproduce this issue; the verification reports I produce from the website open without problem. do you remember with which model JSON and critical test data CSV it was produced?

**Comment by markdouglasphd** [comment]
Hi @SCA-ZMT. Here are the input files. GitHub won't let me upload the json file, but you can generate it with this data. Using these I can't generate the pdf.
I've tried it with other models today with the same outcome.

[SearchSpace 20230501_out4_bad.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11367452/SearchSpace.20230501_out4_bad.csv)
[TestData 20230501_out4_bad.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11367453/TestData.20230501_out4_bad.csv)
[TrainingData 20230501_out4_bad.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11367454/TrainingData.20230501_out4_bad.csv)

**Comment by SCA-ZMT** [comment]
hi @markdouglasphd, thanks for the files. the "modulation" column is missing in the SearchSpace csv, and it's needed for the report table, so the PDF cannot be generated. I will add an error message.

**Comment by SCA-ZMT** [comment]
@maiz I now return a JSON with "error" instead of a file response if something goes wrong

**Comment by markdouglasphd** [comment]
Hi @SCA-ZMT and @odeimaiz,

Thanks for checking this. So the problem is that "Search Space" does not create a modulation column. I guess that this is a problem on the back end that @cbujard needs to fix.

Mark

![2023-05-02 15_09_35-oSPARC - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/131360748/235675825-f5ae10cb-de81-4583-b504-f8b52f9e859c.png)

**Comment by cbujard** [comment]
Yes, I'll generate this modulation column from the snapped computed bw and par.
