### ISSUE TITLE
update caption of QQ plot in model confirmation report

### ISSUE THREAD

**Issue by markdouglasphd** [ITISFoundation/publication-IEC62209#35]
v1.0.12
There are some mistakes in the caption of the QQ plot. Please change it to:
"QQ-plot of the SAR deviations, comparing the probability distributions of the created validation model and the test set. These SAR deviations are expected to be normally distributed. The linear regression line (red) through the resulting points (blue) should be close to the reference line (black)."

![2023-05-01 14_41_08-ModelConfirmationReport (1) pdf - Adobe Acrobat Pro (64-bit)](https://user-images.githubusercontent.com/131360748/235453019-11c4a33f-4a07-4da2-b978-b92783d9f464.png)

**Comment by SCA-ZMT** [comment]
will be fixed by https://github.com/ITISFoundation/IEC62209-service/pull/79
