### ISSUE TITLE
wrong measurement area in 'Analysis & Creation'

### ISSUE THREAD

**Issue by markdouglasphd** [ITISFoundation/publication-IEC62209#45]
There are two problems with the measurement area in the 'Analysis & Creation' window:
1) the measurement area is half of what it should be. See example below, where the measurement area in the 'Training Set Generation' is 80 x 160 mm, but the measurement area in 'Analysis & Creation' is 42 x 84 mm.

As Cedric said, the measurement area (size_x, size_y) should be constrained as follows: 2 xmax <= size_x <= 2 xsup
But what you have done is this: 1 xmax <= size_x <= 1 xsup

2) the default values in this case should be the lower value: size_x = 2 xmax, not the higher value (2 xsup). 
In this example, 2 xmax = 80 mm, so the default should be size_x = 80, not size_x = 84.
Cedric explained this on Mattermost yesterday. Whenever N > max(size_x, size_y), then size_x = 2 xmax, because of the constraints of latin hypercube sampling.
 
![2023-05-04 23_02_02-Presentation1 - PowerPoint](https://user-images.githubusercontent.com/131360748/236330460-07e6b13b-a413-414a-9016-68a9437a84d1.png)

**Comment by markdouglasphd** [comment]
By the way, the constraining part works as expected. Thanks.

**Comment by cbujard** [comment]
This issue does not concern the backend. Just a small tweak in Simone's part.

**Comment by odeimaiz** [comment]
OM todo: Default to xmin and ymin
