### ISSUE TITLE
the 'Confirm' plots do not correspond with the criteria

### ISSUE THREAD

**Issue by markdouglasphd** [ITISFoundation/publication-IEC62209#46]
There is something wrong with the plotting in the 'Confirm' window.
The plots do not correspond to the criteria.
For example, the images below show that Acceptance criteria = Pass but the plot shows Fail.
And the QQ plot values do not match the blue/red text.

This happens when I load many different test set files to look at different results. The files I used are attached. 
Try running many of them and then going back to the original one. You will see that the plots are not the same.
I used the same Model.json file for all checks.

[TestData_measured.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11402250/TestData_measured.csv)
[TestData_measured_bad.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11402252/TestData_measured_bad.csv)
[TestData_out0_other.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11402253/TestData_out0_other.csv)
[TestData_out1_other.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11402254/TestData_out1_other.csv)
[TestData_out2_other.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11402255/TestData_out2_other.csv)
[TestData_out3_other.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11402256/TestData_out3_other.csv)
[TestData_out4_other.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11402257/TestData_out4_other.csv)
[TestData_out5_other.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11402258/TestData_out5_other.csv)
[TestData_out6_other.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11402259/TestData_out6_other.csv)
[TestData_out7_other.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11402260/TestData_out7_other.csv)
[TestData_out8_other.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11402261/TestData_out8_other.csv)
[TestData_out9_other.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11402263/TestData_out9_other.csv)

![2023-05-05 01_00_29-oSPARC - Profile 1 - Microsoft​ Edge](https://user-images.githubusercontent.com/131360748/236348559-5d113ede-e00e-46d4-81cc-56ce4a7484d7.png)
![2023-05-05 01_00_01-oSPARC - Profile 1 - Microsoft​ Edge](https://user-images.githubusercontent.com/131360748/236348565-2079ac55-4cf3-40b9-8772-8b0e2ba3768a.png)

**Comment by SCA-ZMT** [comment]
@odeimaiz I will check if I forgot to reset some of the data I cache in the backend as well...
