### ISSUE TITLE
Load Model should not update model values into Analysis/creation step

### ISSUE THREAD

**Issue by njain76** [ITISFoundation/publication-IEC62209#48]
Hi,
If we load a model in load model step, and then move to Analysis/Creation step, the model name / values from load model step are carried over to Analysis/Creation step.

This is confusing for the user, as he is still only analysing and creating the model.

A short screen video is attached.

Regards,
Nitin

![model error](https://user-images.githubusercontent.com/132723646/236654231-9861b4a5-8e95-49f9-8382-f51a483586fe.gif)

**Comment by SCA-ZMT** [comment]
@odeimaiz @markdouglasphd I would suggest disabling "Training Set Generation", "Load Training Data", and "Analysis & Creation" if a model has been loaded
