### ISSUE TITLE
Create and Analyze step fails for valid input

### ISSUE THREAD

**Issue by njain76** [ITISFoundation/publication-IEC62209#49]
[TrainingData_out9_other.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11414000/TrainingData_out9_other.csv)

Hi,

The attached input training data set has the 10g SAR values normally distributed around the targets (with no preferences to any of the input variables).

But the model creation step fails as nrmse is 33.1%, as against required 25%.

For a normal user, this seems like a valid input, and should be easy to model, so it is difficult to understand why the model generation step fails.

Regards,
Nitin

**Comment by cbujard** [comment]
@markdouglasphd @njain76 we need more info on how this data was generated. In particular if the data was iid randomly generated around the targets as said, there's no spacial autocorrelation and the modeling part is trying to make sense of something that has none. It's generally difficult to reproduce meaningful data without performing measurements.

**Comment by njain76** [comment]
Hi Cedric,

It was generated with the following code:

   sard10g =  np.random.normal(0, 0.25, len(df))       # calculate SAR deviations in dB
    sar10g_meas = sar10g_target * 10**(sard10g/10)   



Regards,
Nitin

**Comment by cbujard** [comment]
Hi Nitin, 

Ty for your input. So while the sar values are autocorrelated (they follow that of the target's), the sard are just random values around 0 that have no spacial dependency (they are independently generated). In the present case the software still attempt to interpret a (badly estimated) correlation function from (inconsistent) patterns. Kriging is not the answer here: if data are independently normally distributed around a fixed mean with a fixed variance, we can instantly provide a chance for the system to fail (provided we can properly estimate this variance), but we cannot provide any specific critical point (the software would currently just guess some). 

We could eventually use the nugget to estimate this variance, but this leads straight into a more general issue:

Our method is meant to work on data that encodes physical properties of a device. This was tested on csar3d and dasy, but it will certainly not work on any kind of inputted data. We probably need to inform the user that measured data is required, and at the same time have the software handle invalid cases.

**Comment by cbujard** [comment]
Hi @njain76 , @markdouglasphd 

I used your above data to reproduce the issue and independently of everything I said here, I found a little bug regrading the nrmse: the bug actually comes from the scikit-gstats package, I recomputed it here myself and it now looks better.
![fig_nitin](https://user-images.githubusercontent.com/118373269/236848372-25785894-0732-48a7-a546-045a3ca44e9c.png)
