### ISSUE TITLE
Measurement area limited to 80 x 160mm, while entered values were 109 x 228mm

### ISSUE THREAD

**Issue by njain76** [ITISFoundation/publication-IEC62209#50]
[TrainingData.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11417596/TrainingData.csv)
![image](https://user-images.githubusercontent.com/132723646/236732841-5a08cc39-5fea-427e-a5d7-57221eac3e07.png)

Hi,

Although we enter 109 x 229mm for the measurement area, the training data generated is limited to a 80 x 160mm area. 

When this training data is fed back to generate the model, the measurement area gets limited to 84 x 168mm, and the user is not allowed to increase the area beyond these values.

Perhaps the measurement area has been reduced, considering the 21mm edge of the 10g cube?

Regards,
Nitin

**Comment by cbujard** [comment]
The second part is perfectly normal. The first part is a bug. @SCA-ZMT can you check the right parameters are properly passed to the Sampler instance that generates the training set (it has to be a new insurance btw). I'll check on my side as well.

**Comment by cbujard** [comment]
So I just checked: in the core part there is no size issue. When the sampler class is instanciated, the desired xmax and ymax values have to be specified as arguments to the constructor (without these the default is 80 x 160 as observed by Nitin). @odeimaiz does the above corrects this issue?
