### ISSUE TITLE
Range / Sill values on Semi Variogram plot

### ISSUE THREAD

**Issue by njain76** [ITISFoundation/publication-IEC62209#52]
![image](https://user-images.githubusercontent.com/132723646/236749703-b0a58c7c-e2e0-4808-9b87-fd337a45b309.png)

Hi,

In the semi variogram plot, the sill value shown is 0.0431, while the range value shown is 2.46.

In my understanding, the sill value is the semi-variance at the range value or vice versa...ie... these should correspond.

Regards,
Nitin

**Comment by cbujard** [comment]
What's called sill in the plot axis is actually the partial sill (sill - nugget). I'll correct this.
